name: GHAction example
'on':
  workflow_dispatch: null
  push:
    tags:
      - v*
jobs:
  ci_step:
    name: 'Build, tag and push Docker image to DockerHub'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source_repo
        uses: actions/checkout@v4
      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: '${{ vars.DOCKERHUB_USERNAME }}/zadanie2'
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   
      - name: QEMU set-up
        uses: docker/setup-qemu-action@v3
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: '${{ vars.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: 'linux/amd64,linux/arm64'
          push: true
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/zadanie2:cache 
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/zadanie2:cache  
          tags: '${{ steps.meta.outputs.tags }}'
      - name: Docker Scout Scan image for vulnerabilities
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves
          platform: linux/amd64
          image: '${{ steps.meta.outputs.tags }}'
          only-severities: 'critical,high'
          exit-code: true
      - name: Log in to GitHub Container Registry
        if: success()
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.MYGITHUB_TOKEN }}'
      - name: Push Docker image to GitHub Container Registry
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: >-
            ghcr.io/${{ vars.MYGITHUB_LOWERCASE_USERNAME }}/zadanie2:${{env.DOCKER_METADATA_OUTPUT_VERSION }}
